"""empty message

Revision ID: 09101c69408a
Revises: 445da3303e41
Create Date: 2023-05-08 10:56:31.376991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09101c69408a'
down_revision = '445da3303e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
