"""empty message

Revision ID: 1af5cd55e993
Revises: 09101c69408a
Create Date: 2023-05-08 11:10:09.218721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af5cd55e993'
down_revision = '09101c69408a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'restaurant_id')
    # ### end Alembic commands ###
